### ISSUE TITLE
Hiding slider when scrolling is completed after 1 sec

### ISSUE THREAD

**Issue by happyByNature** [jamesflorentino/nanoScrollerJS#153]
Hello!

If somebody interested how to hide slider when the scrolling is completed, please consider the following code (fixed from that was found here in another issues):

CSS:

``` css
#wrapper .show, .hide { transition: opacity 100ms linear; }
#wrapper .show { opacity: 1; }
#wrapper .hide { opacity: 0; }
#wrapper .slow.hide { transition: opacity 100ms linear 300ms; } /* fourth argument is the delay */
```
# wrapper is div-container just to avoid overriding global "show", "hide" styles...

Javascript:

``` javascript
var glNotifScroller = $("#abc.nano");

glNotifScroller.nanoScroller();

glNotifScroller.find('.content').on("scroll", function () {
    clearTimeout(glNotifScroller.data("timerId"));
    glNotifScroller.find('.slider').removeClass("slow hide");
    glNotifScroller.data({
        timerId: setTimeout(function() {
            glNotifScroller.find('.slider').addClass("slow hide");
        }, 1000)
    });
});
```

Would like to see that feature native)
