### ISSUE TITLE
Scrollbar not visible -- .pane keeps display: none; in chrome

### ISSUE THREAD

**Issue by flip111** [jamesflorentino/nanoScrollerJS#189]
I'm having the same issue as the guy who made this SO question http://stackoverflow.com/questions/15155774/nanoscroller-js-slider-pane-not-showing-in-chrome-solution-found so i figured i would report it as an issue ...

This only seems to occur when the element where to the nanoscroller is applied has not been placed in the DOM yet. Firefox doesn't have this problem.

**Comment by brauliobo** [comment]
got the same here and calling it again didn't work...
had to show it manually:
```scss
.nano {                                                                                                                                                                                      
    .nano-content {                                                                                                                                                                          
    }                                                                                                                                                                                        
    .nano-pane {                                                                                                                                                                             
        background: #888;                                                                                                                                                                    
    }                                                                                                                                                                                        
    .nano-slider {                                                                                                                                                                           
        background: #111;                                                                                                                                                                    
    }                                                                                                                                                                                        
}
```
